# Generated by Django 4.0.3 on 2022-04-07 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('members', models.ManyToManyField(limit_choices_to={'is_superuser': False}, related_name='exp_groups', through='account.Transaction', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(limit_choices_to={'is_superuser': False}, on_delete=django.db.models.deletion.PROTECT, related_name='my_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense Group',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('detail', models.TextField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gp_expenses', to='home.expensegroup')),
            ],
            options={
                'verbose_name': 'Expense',
                'ordering': ('group', 'title'),
            },
        ),
    ]
