# Generated by Django 4.0.3 on 2022-03-30 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='contributor',
            field=models.ManyToManyField(limit_choices_to={'is_superuser': False}, related_name='expense_contributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='pay_by',
            field=models.ForeignKey(limit_choices_to={'is_superuser': False}, on_delete=django.db.models.deletion.PROTECT, related_name='paid_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensegroup',
            name='members',
            field=models.ManyToManyField(limit_choices_to={'is_superuser': False}, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensegroup',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'is_superuser': False}, on_delete=django.db.models.deletion.PROTECT, related_name='my_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
