# Generated by Django 4.0.3 on 2022-03-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'User Account'},
        ),
        migrations.AlterModelOptions(
            name='userexpense',
            options={'verbose_name': 'User Expense'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': 'UserGroup'},
        ),
    ]
