# Generated by Django 4.0.3 on 2022-03-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_useraccount_options_alter_userexpense_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': 'User Group'},
        ),
    ]
